var N = null;var sourcesIndex = {};
sourcesIndex["calypso"] = {"name":"","dirs":[{"name":"commands","files":["explain.rs","internal.rs","mod.rs"]}],"files":["buildinfo.rs","main.rs"]};
sourcesIndex["calypso_ast"] = {"name":"","dirs":[{"name":"expr","files":["mod.rs"]}],"files":["lib.rs","pretty.rs","traverse.rs"]};
sourcesIndex["calypso_base"] = {"name":"","dirs":[{"name":"streams","files":["generic.rs","str.rs"]}],"files":["lib.rs","session.rs","span.rs","streams.rs","symbol.rs","ui.rs"]};
sourcesIndex["calypso_diagnostic"] = {"name":"","files":["diagnostic.rs","error.rs","lib.rs","report.rs","types.rs"]};
sourcesIndex["calypso_error"] = {"name":"","files":["lib.rs"]};
sourcesIndex["calypso_parsing"] = {"name":"","dirs":[{"name":"lexer","files":["helpers.rs","ident_kw.rs","lit.rs","num.rs","scan.rs","types.rs","ws.rs"]},{"name":"parser","files":["expr.rs","grammar.rs","tokens.rs"]},{"name":"pretty","files":["lexer.rs","mod.rs"]}],"files":["lexer.rs","lib.rs","parser.rs"]};
sourcesIndex["calypso_repl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["calypso_util"] = {"name":"","files":["lib.rs"]};
sourcesIndex["saturnvm"] = {"name":"","files":["lib.rs","ops.rs"]};
createSourceSidebar();
